# from ontonotes_srl.srl_bert import SrlBert
from ontonotes_srl.srl_bert_bilstm import SrlBertBilstm
# from ontonotes_srl.semantic_role_labeler import SemanticRoleLabelerPredictor
from ontonotes_srl.nn_semantic_role_labeler import NNSemanticRoleLabelerPredictor
# from ontonotes_srl.semantic_role_labeling import SrlReader
from ontonotes_srl.ontonotes_srl_nn_reader import SrlNNReader
